### ISSUE TITLE
ImportError: No module named 'BlynkTimer'

### ISSUE THREAD

**Issue by lucavallin** [vshymanskyy/blynk-library-python#34]
BlynkTimer seems to be broken somehow, cannot import it.

```
pi@raspberrypi:~/hytta $ python3 main.py
    ___  __          __
   / _ )/ /_ _____  / /__
  / _  / / // / _ \/  '_/
 /____/_/\_, /_//_/_/\_\
        /___/ for Python v0.2.0 (Linux)

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from BlynkTimer import BlynkTimer
ImportError: No module named 'BlynkTimer'
```

**Comment by BradenM** [comment]
Sorry about that! I forgot to add the module to setup.py.

Just opened a tiny PR to fix it.

**Comment by lucavallin** [comment]
Awesome, thanks!

**Comment by vitormhenrique** [comment]
I'm also having the same issue, any way to fix it?

**Comment by BradenM** [comment]
@vitormhenrique Seems that this repo is no longer being maintained. I would checkout [lib-python](https://github.com/blynkkk/lib-python), which is an actively maintained Blynkkk owned repo for python.

Otherwise, you can simply download the `BlynkTimer.py` file and upload it to your pyboard under `/lib/BlynkTimer.py`. There it will automatically be picked up by micropython and you can import it as so: `from BlynkTimer import timer`

**Comment by vitormhenrique** [comment]
I actually was using the other library and got the same error! just realized that!

**Comment by BradenM** [comment]
@vitormhenrique Haha, can't blame you, there is a bit of confusion with two repos like this. On the other repo, the timer class is named `Timer` so it should be `from blynktimer import Timer` -- see [here](https://github.com/blynkkk/lib-python/blob/master/TIMERS.md)

if that doesn't fix your problem however, I would open an issue on (lib-python)[https://github.com/blynkkk/lib-python].

**Comment by vitormhenrique** [comment]
Thanks!

I noticed that their setup.py does not include the blynktimer.

py_modules=['blynklib']

I already forked the repo and fixed.

Thanks for the help!

**Comment by shahidadnaan2000** [comment]
I got it fixed !!!!!!!!!

copy the  BlynkLib in the same folder where your code is. It should fix the problem

NOTE: This problem is happening because while installing bylnk by default python2 is used but for other application we are using python3 where the library is not getting copied.

**************************************************

This steps are for only new installed raspbian : 

Suggested to follow :
Step 1 : With the new install raspbian on PI
Go to the link 

 https://learn.sparkfun.com/tutorials/python-programming-tutorial-getting-started-with-the-raspberry-pi/configure-your-pi

follow along from 
Use Python 3
Till the end 

Step 2: 
install the blynk now and it should work 

***************************************************

Still any issue please write to be directly at shahid.adnaan2000@gmail.com will help you ASAP(FREE).
